# Generated by Django 4.2.7 on 2024-05-18 15:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftweb', '0002_cryptopayment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopayment',
            name='proof_of_pay',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='zorevina'),
        ),
    ]
