# Generated by Django 4.2.7 on 2024-05-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='bitcoin',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='bitcoins',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='ethereum',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='ethereums',
        ),
    ]
